FROM golang:1.15-alpine

RUN apk add --no-cache build-base

RUN mkdir -p /go/src/github.com/nemonicgod/terraforms-api
WORKDIR /go/src/github.com/nemonicgod/terraforms-api

COPY go.mod .
COPY go.sum .

RUN go get github.com/cosmtrek/air@b538c70423fb3590435c003dda15bf6a2f61187c && \
    go mod download && \
    go mod tidy && \
    go mod vendor

ADD . /go/src/github.com/nemonicgod/terraforms-api

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
ENV ENVIRONMENT local